setwd('/Users/lakshmi_shetty/Desktop/664-project')
getwd()
Finaldata<-read.csv('./clusterfinal.csv')
install.packages("wordcloud")
install.packages("RColorBrewer")
library("wordcloud")
library("RColorBrewer")
install.packages("tm")
library("tm")
#cluster-1
Clus1<- Corpus(VectorSource(Finaldata$Cluster.1))
data1 <- TermDocumentMatrix(Clus1)
matr<- as.matrix(data1)
arrange <- sort(rowSums(matr),decreasing=TRUE)
dc1<- data.frame(word = names(arrange),freq=arrange)
head(dc1, 10)
#cluster-2
Clus2<- Corpus(VectorSource(Finaldata$cluster.2))
data2 <- TermDocumentMatrix(Clus2)
matri2<- as.matrix(data2)
arrange2 <- sort(rowSums(matri2),decreasing=TRUE)
dc2<- data.frame(word = names(arrange2),freq=arrange2)
head(dc2, 10)
#cluster-2
Clus3<- Corpus(VectorSource(Finaldata$cluster.3))
data3 <- TermDocumentMatrix(Clus3)
matri3<- as.matrix(data3)
arrange3 <- sort(rowSums(matri3),decreasing=TRUE)
dc3<- data.frame(word = names(arrange3),freq=arrange3)
head(dc3, 10)

